### ISSUE TITLE
'Sample Id' of selected cells in MERFISH datasets in the online viewer don't match cell labels in h5ad data

### ISSUE THREAD

**Issue by paulacauhy** [AllenInstitute/abc_atlas_access#57]
Hi! I've been using the Brain Knowledge Platform to play with the MERFISH whole mouse brain data, and I have a question about the Sample Id annotation when using the Cell Selection tool. When selecting a few cells, it opens a panel on the right with information on the selected cells, where we can see a Sample ID that looks like this: '18fa5e5b-e460-4c30-8f95-2ea4e8390e1b' . I want to check the entire data for this cell from this experiment, but in the h5ad file I accessed in the AWB bucket, the cell_label information does not match the Sample Id at all. Could you please provide more information on how I can find the full transcriptomic data for the cells I selected in the MERFISH viewer? 

Thank you!

**Comment by morriscb** [comment]
Hi Paula,

The id you're looking at looks to be hash id specific to the ABC Atlas and not something that's in the data release served here. Could you please post your question on the Allen Community forum here? https://community.brain-map.org/c/how-to/abc-atlas/19

Thanks!

**Comment by morriscb** [comment]
Hi Paula,

The latest version of the data just pushed now has sample ids in the cell_metadata. Here's an example notebook on using the IDs. https://alleninstitute.github.io/abc_atlas_access/notebooks/abc_atlas_selection_example.html
