### ISSUE TITLE
How do I download specific cell type gene expression data for WHB?

### ISSUE THREAD

**Issue by ayeTown** [AllenInstitute/abc_atlas_access#58]
Thank you for this awesome tool! Is there a way to download a subset of the gene expression raw data? For example, looking at a specific cell type of interest such as Astrocytes. I saw that you have the capability to download a subset of genes, but I'd like to download the whole gene expression raw data for a given cell type. Thanks for your time/help.

**Comment by morriscb** [comment]
Answered on the Allen Community forum: https://community.brain-map.org/t/how-do-i-download-specific-cell-type-gene-expression-data-from-whb/3648. Closing here.
